//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Red.WorkPoint.ProjectPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Red.WorkPoint.ProjectPlugin.Resources.LocalStrings", typeof(LocalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed bid.
        /// </summary>
        internal static string BillingTypeFix {
            get {
                return ResourceManager.GetString("BillingTypeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-billable.
        /// </summary>
        internal static string BillingTypeNB {
            get {
                return ResourceManager.GetString("BillingTypeNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and materials.
        /// </summary>
        internal static string BillingTypeTM {
            get {
                return ResourceManager.GetString("BillingTypeTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string ButtonDeleteAuth {
            get {
                return ResourceManager.GetString("ButtonDeleteAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string ButtonPublish {
            get {
                return ResourceManager.GetString("ButtonPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string CommandOpen {
            get {
                return ResourceManager.GetString("CommandOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string CommandPublish {
            get {
                return ResourceManager.GetString("CommandPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string CommandSync {
            get {
                return ResourceManager.GetString("CommandSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred..
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading actual hours....
        /// </summary>
        internal static string MessageActualSync {
            get {
                return ResourceManager.GetString("MessageActualSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} to project team....
        /// </summary>
        internal static string MessageAddingTeamMember {
            get {
                return ResourceManager.GetString("MessageAddingTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string MessageAuth {
            get {
                return ResourceManager.GetString("MessageAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} contains assignments with the same emails . Task data will not be synced..
        /// </summary>
        internal static string MessageDuplicateEmailsInAssignmentsByTask {
            get {
                return ResourceManager.GetString("MessageDuplicateEmailsInAssignmentsByTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was canceled..
        /// </summary>
        internal static string MessageOperationWasCanceled {
            get {
                return ResourceManager.GetString("MessageOperationWasCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating project....
        /// </summary>
        internal static string MessageProjectIsCreating {
            get {
                return ResourceManager.GetString("MessageProjectIsCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating project....
        /// </summary>
        internal static string MessageProjectIsUpdating {
            get {
                return ResourceManager.GetString("MessageProjectIsUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project was published successfully..
        /// </summary>
        internal static string MessagePublishDone {
            get {
                return ResourceManager.GetString("MessagePublishDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0} from project team....
        /// </summary>
        internal static string MessageRemovingTeamMember {
            get {
                return ResourceManager.GetString("MessageRemovingTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing resource plan to Timetta....
        /// </summary>
        internal static string MessageResourcePlanSync {
            get {
                return ResourceManager.GetString("MessageResourcePlanSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project End date is less than the Start date, the resource plan will not be synced..
        /// </summary>
        internal static string MessageStartDateIsAfterEndDate {
            get {
                return ResourceManager.GetString("MessageStartDateIsAfterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has been updated successfully..
        /// </summary>
        internal static string MessageSyncDone {
            get {
                return ResourceManager.GetString("MessageSyncDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization is not possible..
        /// </summary>
        internal static string MessageSynchronizationIsNotPossible {
            get {
                return ResourceManager.GetString("MessageSynchronizationIsNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing tasks to Timetta....
        /// </summary>
        internal static string MessageTaskSync {
            get {
                return ResourceManager.GetString("MessageTaskSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project contains resources with the same emails. .
        /// </summary>
        internal static string MessageTeamHasDuplicateEmails {
            get {
                return ResourceManager.GetString("MessageTeamHasDuplicateEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing team to Timetta....
        /// </summary>
        internal static string MessageTeamSync {
            get {
                return ResourceManager.GetString("MessageTeamSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default role was not found. Synchronization is not possible..
        /// </summary>
        internal static string MessageThereIsNoDefaultRole {
            get {
                return ResourceManager.GetString("MessageThereIsNoDefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was not found in Timetta and cannot be exported..
        /// </summary>
        internal static string MessageUserEmailNotFound {
            get {
                return ResourceManager.GetString("MessageUserEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import actual hours.
        /// </summary>
        internal static string SettingsImprotActualHours {
            get {
                return ResourceManager.GetString("SettingsImprotActualHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data will be synchronized for the period from {0} and to {1}.
        /// </summary>
        internal static string SyncPeriodTemplate {
            get {
                return ResourceManager.GetString("SyncPeriodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish project.
        /// </summary>
        internal static string TitlePublish {
            get {
                return ResourceManager.GetString("TitlePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync project.
        /// </summary>
        internal static string TitleSync {
            get {
                return ResourceManager.GetString("TitleSync", resourceCulture);
            }
        }
    }
}
